---
name: Validate OpenAPI Spec
on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Validate configuration
        run: |
          redocly check-config

      - name: Validate specification
        run: |
          redocly lint
